kali_rest_rest:
    resource: "@KaliRestRestBundle/Controller/"
    type:     annotation
    prefix:   /

kali_rest_default:
    resource: "@KaliRestDefaultBundle/Controller/"
    type:     annotation
    prefix:   /

kali_back_command:
    resource: "@KaliBackCommandBundle/Controller/"
    type:     annotation
    prefix:   /

kali_back_image:
    resource: "@KaliBackImageBundle/Controller/"
    type:     annotation
    prefix:   /

kali_back_parameter:
    resource: "@KaliBackParameterBundle/Controller/"
    type:     annotation
    prefix:   /

kali_back_product:
    resource: "@KaliBackProductBundle/Controller/"
    type:     annotation
    prefix:   /

kali_back_user:
    resource: "@KaliBackUserBundle/Controller/"
    type:     annotation
    prefix:   /
    
kali_back_theme:
    resource: "@KaliBackThemeBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

#REST
rest :
    type : rest
    resource : "routing_rest.yml"
    prefix : /api