security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_CLIENT:            ROLE_CLIENT
        ROLE_SERVICE_CLIENT :   ROLE_SERVICE_CLIENT
        ROLE_SERVICE_PRODUCT :  ROLE_SERVICE_PRODUCT
        ROLE_ADMIN_KALI:        ROLE_ADMIN_KALI

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        login_firewall:
            pattern:    ^/login$
            anonymous:  ~

        secured_area:
            pattern:    ^/
            access_denied_url: /forbidden
            http_basic:
                realm: "Zone de sécurité"
            anonymous: false

            #formulaire de connexion
            form_login:
                login_path:  /login
                check_path:  /login_check
                always_use_default_target_path: false
                default_target_path: /user/list
            logout:
                path:   /logout
                target: /


    access_control:
            - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/, role: ROLE_ADMIN }