slider :
  type: rest
  resource:     "KaliRestRestBundle:Slider"
  name_prefix:  api_

product :
  type: rest
  resource:     "KaliRestRestBundle:Product"
  name_prefix:  api_
  
category :
  type: rest
  resource:     "KaliRestRestBundle:Category"
  name_prefix:  api_
    
user :
  type: rest
  resource:     "KaliRestRestBundle:User"
  name_prefix:  api_