<?php

namespace Kali\Back\ProductBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CaracteristicRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CaracteristicRepository extends EntityRepository
{
    /**
     * 
     * @description Retourne la liste des caractéristiques d'un produit
     * @param Product $product
     * @return array(Caracteristic)
     */
    public function findByProduct(Product $product) {
        return $this->_em->createQuery('SELECT c FROM KaliBackProductBundle:Caracteristic c WHERE c.products=:product')
                        ->setParameter('product', $product)
                        ->getResult();
    }
}
