<?php

namespace Kali\Back\ProductBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{
    /**
     * 
     * @description Retourne la liste des 10 produits les plus vendus
     * @return array(Product)
     */
    public function findPopular()
    {
        return "toto";
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p FROM KaliBackProductBndle:Product p'
            )
            ->getResult();
    }
}
