<?php

namespace Kali\Back\ProductBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProductCommandRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductCommandRepository extends EntityRepository
{
}
