<?php

namespace Kali\Back\ProductBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PromotionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PromotionRepository extends EntityRepository
{
    /**
     * 
     * @description Retourne la liste des coupons disponible
     * @return array(Promotion)
     */
    public function listPromotionDisponible() {
        return $this->_em->createQuery('SELECT p FROM KaliBackProductBundle:Promotion p WHERE p.used=0')
                        ->getResult();
    }
}
