<?php

namespace Kali\Back\ProductBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SenderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SenderRepository extends EntityRepository {

    /**
     * 
     * @description Retourne un transporteur acceptant le poids et la taille en paramètre
     * @param float $sizeMax
     * @param float $weightMAx
     * @return array(Product)
     */
    public function findSenderByWeightAndSize($sizeMax, $weightMax) {
        try {
            $query = $this->getEntityManager()
                    ->createQuery(
                            'SELECT s FROM KaliBackProductBundle:Sender s WHERE s.maxSize>=:maxSize AND s.maxWeight>=:maxWeight'
                    )
                    ->setParameters(array(
                        'maxSize' => $sizeMax,
                        'maxWeight' => $weightMax,
                    ))
                    ->setMaxResults(1);

            return $query->getSingleResult();
        } catch (\Doctrine\Orm\NoResultException $e) {
            return null;
        }
    }

}
