<?php

namespace Kali\Back\ParameterBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ParameterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParameterRepository extends EntityRepository
{

    public function find($id)
    {
        return $this->getEntityManager()

            ->createQuery('SELECT u FROM KaliBackParameterBundle:Parameter u')
            ->where ('u.id = :id')
            ->getResult();



    }


}
